vich_uploader:
    db_driver: orm

    mappings:
        profils:
            uri_prefix: /images/profils
            upload_destination: '%kernel.project_dir%/public/images/profils'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        csv:
            uri_prefix: /fichierCSV
            upload_destination: '%kernel.project_dir%/public/fichierCSV'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true